import re

with open('src/data/iplLegends.js', 'r', encoding='utf-8') as f:
    content = f.read()

players_data = """export const iplPlayers = [
  { name: 'Virat Kohli', team: 'RCB', role: 'Batsman', runs: 8661, wickets: 4, catches: 114, matches: 267, sixes: 290, fifties: 54, hundreds: 9, emoji: '👑', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Virat_Kohli_in_PMO_New_Delhi.jpg/330px-Virat_Kohli_in_PMO_New_Delhi.jpg' },
  { name: 'MS Dhoni', team: 'CSK', role: 'WK-Batsman', runs: 5439, wickets: 0, catches: 178, matches: 278, sixes: 264, fifties: 24, hundreds: 0, emoji: '🦁', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/MS_Dhoni_%28Prabhav_%2723_-_RiGI_2023%29.jpg/330px-MS_Dhoni_%28Prabhav_%2723_-_RiGI_2023%29.jpg' },
  { name: 'Rohit Sharma', team: 'MI', role: 'Batsman', runs: 7329, wickets: 15, catches: 75, matches: 280, sixes: 323, fifties: 49, hundreds: 2, emoji: '🏏', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Prime_Minister_Of_Bharat_Shri_Narendra_Damodardas_Modi_with_Shri_Rohit_Gurunath_Sharma_%28Cropped%29.jpg/330px-Prime_Minister_Of_Bharat_Shri_Narendra_Damodardas_Modi_with_Shri_Rohit_Gurunath_Sharma_%28Cropped%29.jpg' },
  { name: 'Suresh Raina', team: 'CSK', role: 'Batsman', runs: 5528, wickets: 25, catches: 109, matches: 205, sixes: 203, fifties: 39, hundreds: 1, emoji: '💛', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Suresh_Raina_grace_the_%27Salaam_Sachin%27_conclave.jpg/330px-Suresh_Raina_grace_the_%27Salaam_Sachin%27_conclave.jpg' },
  { name: 'Jasprit Bumrah', team: 'MI', role: 'Bowler', runs: 65, wickets: 180, catches: 18, matches: 147, sixes: 2, fifties: 0, hundreds: 0, emoji: '🔥', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Jasprit_Bumrah_in_PMO_New_Delhi.jpg/330px-Jasprit_Bumrah_in_PMO_New_Delhi.jpg' },
  { name: 'AB de Villiers', team: 'RCB', role: 'Batsman', runs: 5162, wickets: 0, catches: 83, matches: 184, sixes: 251, fifties: 40, hundreds: 3, emoji: '🎯', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/AB_de_villiers_%28cropped%29.jpg/330px-AB_de_villiers_%28cropped%29.jpg' },
  { name: 'Chris Gayle', team: 'RCB/PBKS', role: 'Batsman', runs: 4965, wickets: 22, catches: 47, matches: 142, sixes: 357, fifties: 31, hundreds: 6, emoji: '💥', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Two_views_of_Chris_Gayle_%2848020785077%29.jpg/330px-Two_views_of_Chris_Gayle_%2848020785077%29.jpg' },
  { name: 'Ravindra Jadeja', team: 'CSK', role: 'All-rounder', runs: 2950, wickets: 160, catches: 88, matches: 240, sixes: 115, fifties: 5, hundreds: 0, emoji: '⚔️', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/PM_Shri_Narendra_Modi_with_Ravindra_Jadeja_%28Cropped%29.jpg/330px-PM_Shri_Narendra_Modi_with_Ravindra_Jadeja_%28Cropped%29.jpg' },
  { name: 'David Warner', team: 'SRH/DC', role: 'Batsman', runs: 6920, wickets: 2, catches: 68, matches: 196, sixes: 245, fifties: 61, hundreds: 4, emoji: '🇦🇺', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/DAVID_WARNER_%2811704782453%29.jpg/330px-DAVID_WARNER_%2811704782453%29.jpg' },
  { name: 'Andre Russell', team: 'KKR', role: 'All-rounder', runs: 2500, wickets: 110, catches: 48, matches: 127, sixes: 208, fifties: 8, hundreds: 0, emoji: '💪', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Andre_Russell_cropped.jpg/330px-Andre_Russell_cropped.jpg' },
  { name: 'Sunil Narine', team: 'KKR', role: 'All-rounder', runs: 1800, wickets: 185, catches: 44, matches: 191, sixes: 112, fifties: 5, hundreds: 1, emoji: '🌀', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Sunil_Narine_cropped.jpg/300px-Sunil_Narine_cropped.jpg' },
  { name: 'Shikhar Dhawan', team: 'PBKS', role: 'Batsman', runs: 6769, wickets: 0, catches: 84, matches: 222, sixes: 148, fifties: 47, hundreds: 2, emoji: '😎', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/SHIKHAR_DHAWAN_%2816005494418%29.jpg/330px-SHIKHAR_DHAWAN_%2816005494418%29.jpg' },
  { name: 'KL Rahul', team: 'LSG', role: 'WK-Batsman', runs: 4950, wickets: 0, catches: 68, matches: 145, sixes: 185, fifties: 40, hundreds: 4, emoji: '🧤', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/KL_Rahul_at_Femina_Miss_India_2018_Grand_Finale_%28cropped%29.jpg/330px-KL_Rahul_at_Femina_Miss_India_2018_Grand_Finale_%28cropped%29.jpg' },
  { name: 'Yuzvendra Chahal', team: 'RR', role: 'Bowler', runs: 72, wickets: 205, catches: 22, matches: 167, sixes: 3, fifties: 0, hundreds: 0, emoji: '🎳', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Yuzvendra_Chahal_in_PMO_New_Delhi.jpg/330px-Yuzvendra_Chahal_in_PMO_New_Delhi.jpg' },
  { name: 'Jos Buttler', team: 'RR', role: 'WK-Batsman', runs: 3900, wickets: 0, catches: 52, matches: 104, sixes: 190, fifties: 24, hundreds: 7, emoji: '🦊', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Jos_Buttler_in_2023.jpg/330px-Jos_Buttler_in_2023.jpg' },
  { name: 'Rashid Khan', team: 'GT', role: 'Bowler', runs: 550, wickets: 148, catches: 30, matches: 121, sixes: 38, fifties: 0, hundreds: 0, emoji: '🇦🇫', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Rashid_Khan.jpg/330px-Rashid_Khan.jpg' },
  { name: 'Shubman Gill', team: 'GT', role: 'Batsman', runs: 4482, wickets: 0, catches: 52, matches: 131, sixes: 125, fifties: 32, hundreds: 4, emoji: '🦊', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Shubman_Gill_2023_%28cropped%29.jpg/330px-Shubman_Gill_2023_%28cropped%29.jpg' },
  { name: 'Ruturaj Gaikwad', team: 'CSK', role: 'Batsman', runs: 2839, wickets: 0, catches: 38, matches: 85, sixes: 107, fifties: 22, hundreds: 2, emoji: '🦁', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Ruturaj_Gaikwad.jpeg/330px-Ruturaj_Gaikwad.jpeg' },
  { name: 'Travis Head', team: 'SRH', role: 'Batsman', runs: 1539, wickets: 3, catches: 18, matches: 52, sixes: 77, fifties: 10, hundreds: 1, emoji: '🧡', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Travis_Head_bowling_at_Perth_Stadium%2C_First_Test_Australia_versus_West_Indies%2C_2_December_2022_03_%28cropped%29.jpg/330px-Travis_Head_bowling_at_Perth_Stadium%2C_First_Test_Australia_versus_West_Indies%2C_2_December_2022_03_%28cropped%29.jpg' },
  { name: 'Yashasvi Jaiswal', team: 'RR', role: 'Batsman', runs: 2536, wickets: 0, catches: 28, matches: 80, sixes: 107, fifties: 18, hundreds: 2, emoji: '🦊', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Yashasvi_Jaiswal_in_PMO_New_Delhi.jpg/330px-Yashasvi_Jaiswal_in_PMO_New_Delhi.jpg' },
  { name: 'Pat Cummins', team: 'SRH', role: 'All-rounder', runs: 641, wickets: 87, catches: 22, matches: 79, sixes: 33, fifties: 3, hundreds: 0, emoji: '🇦🇺', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Pat_Cummins.jpg/330px-Pat_Cummins.jpg' },
];"""

content = re.sub(r"export const iplPlayers = \[.*?\];", players_data, content, flags=re.DOTALL)

with open('src/data/iplLegends.js', 'w', encoding='utf-8') as f:
    f.write(content)

print("Updated iplLegends.js with correct exact player data!")
